services:
  db:
    image: postgres:16
    container_name: my_drupal_ubuntu_db
    restart: always
    environment:
      POSTGRES_DB: drupal10
      POSTGRES_USER: drupal10
      POSTGRES_PASSWORD: drupal10
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  drupal:
    build:
      context: .
      dockerfile: ./php-ubuntu/Dockerfile
    container_name: my_drupal_ubuntu_app
    restart: always
    ports:
      - "8088:80"
    volumes:
      - ./web:/var/www/web
      - ./vendor:/var/www/vendor
      - ./php.ini:/etc/php/8.2/fpm/conf.d/99-custom.ini
      - ./config:/var/www/config
      - ./private:/var/www/private
    environment:
      PHP_MEMORY_LIMIT: 256M
      DRUPAL_DB_HOST: db
      DRUPAL_DB_PORT: 3306
      DRUPAL_DB_NAME: drupal10
      DRUPAL_DB_USER: drupal10
      DRUPAL_DB_PASSWORD: drupal10
    depends_on:
      - db

    # dns:
    #   - 140.20.254.10
    #   - 140.20.254.11
    #   - 140.20.254.12
    #   - 140.20.254.13
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: my_drupal_phpmyadmin
  #   restart: always
  #   ports:
  #     - "8081:80"  # phpMyAdmin at http://localhost:8081
  #   environment:
  #     PMA_HOST: db
  #     PMA_PORT: 3306
  #   depends_on:
  #     - db

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
volumes:
  db_data:
